FROM debian:bookworm-slim

RUN apt update && apt install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*

RUN mkdir /app
COPY target/aarch64-unknown-linux-gnu/binrelease/server /app/server
COPY target/site /app/target/site
COPY Cargo.toml /app/Cargo.toml

WORKDIR /app
ENTRYPOINT ["/app/server"]