[package]
name = "server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app = { path = "../app", default-features = false, features = ["ssr"] }
leptos = { workspace = true, features = ["ssr"] }
leptos_router = { workspace = true, features = ["ssr"] }
leptos_axum.workspace = true

axum.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
common = { path = "../common", default-features = false, features = ["ssr"] }
thiserror.workspace = true
serde.workspace = true
bincode.workspace = true
uuid.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
tracing-journald.workspace = true

dotenvy.workspace = true

rust-call-client.workspace = true

openssl.workspace = true

[features]
ssr = [] # No user, only here to satisfy rust analyzer
