[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { workspace = true, optional = true }
rand = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
tracing = { workspace = true }
bincode = { workspace = true }

axum = { workspace = true, optional = true }
futures = { workspace = true, optional = true }
unicase = { workspace = true, optional = true }

base64 = { workspace = true, optional = true }
hmac = { workspace = true, optional = true }
sha1 = { workspace = true, optional = true }

[features]
default = []
hydrate = []
ssr = [
    "dep:tokio",
    "dep:axum",
    "dep:futures",
    "dep:unicase",
    "dep:base64",
    "dep:hmac",
    "dep:sha1",
]
